/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gtvet_ict_management_system;

/**
 *
 * @author Tshabalala.M
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        Container = new javax.swing.JPanel();
        Right = new javax.swing.JPanel();
        lbLogos = new javax.swing.JLabel();
        lbICTLogo = new javax.swing.JLabel();
        lbDesignedBy = new javax.swing.JLabel();
        lbCopyright = new javax.swing.JLabel();
        Left = new javax.swing.JPanel();
        lbLogin = new javax.swing.JLabel();
        lbEmail = new javax.swing.JLabel();
        tfEmail = new javax.swing.JTextField();
        lbPassword = new javax.swing.JLabel();
        pfPassword = new javax.swing.JPasswordField();
        btLogin = new javax.swing.JButton();
        lbForgotPass = new javax.swing.JLabel();
        btReset = new javax.swing.JButton();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("LOGIN");
        setBackground(new java.awt.Color(204, 204, 204));
        setPreferredSize(new java.awt.Dimension(600, 400));

        Container.setBackground(new java.awt.Color(255, 255, 255));
        Container.setPreferredSize(new java.awt.Dimension(600, 400));
        Container.setLayout(null);

        Right.setBackground(new java.awt.Color(0, 153, 255));
        Right.setMinimumSize(new java.awt.Dimension(300, 400));
        Right.setPreferredSize(new java.awt.Dimension(300, 400));

        lbLogos.setIcon(new javax.swing.ImageIcon("C:\\Users\\TSHABALALA.M\\OneDrive - Goldfields TVET College\\Documents\\NETBEANS PROJECTS\\GTVET_ICT_MANAGEMENT_SYSTEM\\GTVET_ICT_MANAGEMENT_SYSTEM\\GTVET_ICT_MANAGEMENT_SYSTEM\\src\\icons\\logo.png")); // NOI18N

        lbICTLogo.setIcon(new javax.swing.ImageIcon("C:\\Users\\TSHABALALA.M\\OneDrive - Goldfields TVET College\\Documents\\NETBEANS PROJECTS\\GTVET_ICT_MANAGEMENT_SYSTEM\\GTVET_ICT_MANAGEMENT_SYSTEM\\GTVET_ICT_MANAGEMENT_SYSTEM\\src\\icons\\ict ms.png")); // NOI18N

        lbDesignedBy.setFont(new java.awt.Font("Segoe UI Light", 0, 10)); // NOI18N
        lbDesignedBy.setForeground(new java.awt.Color(204, 204, 204));
        lbDesignedBy.setText(" Designed by Macaza Godfrey Tshabalala All rights reserved");

        lbCopyright.setFont(new java.awt.Font("Segoe UI Light", 0, 10)); // NOI18N
        lbCopyright.setForeground(new java.awt.Color(204, 204, 204));
        lbCopyright.setText("copyright © Goldfields TVET College |");

        javax.swing.GroupLayout RightLayout = new javax.swing.GroupLayout(Right);
        Right.setLayout(RightLayout);
        RightLayout.setHorizontalGroup(
            RightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RightLayout.createSequentialGroup()
                .addGroup(RightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(RightLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(lbLogos))
                    .addGroup(RightLayout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addGroup(RightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbCopyright, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbICTLogo))))
                .addGap(10, 10, 10))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RightLayout.createSequentialGroup()
                .addComponent(lbDesignedBy, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        RightLayout.setVerticalGroup(
            RightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RightLayout.createSequentialGroup()
                .addComponent(lbLogos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbICTLogo)
                .addGap(32, 32, 32)
                .addComponent(lbCopyright)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbDesignedBy)
                .addContainerGap(58, Short.MAX_VALUE))
        );

        Container.add(Right);
        Right.setBounds(0, 0, 300, 400);

        Left.setBackground(new java.awt.Color(255, 255, 255));
        Left.setMinimumSize(new java.awt.Dimension(300, 400));
        Left.setPreferredSize(new java.awt.Dimension(300, 400));

        lbLogin.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbLogin.setForeground(new java.awt.Color(0, 153, 255));
        lbLogin.setText("LOGIN");

        lbEmail.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lbEmail.setForeground(new java.awt.Color(102, 102, 102));
        lbEmail.setText("Email");

        tfEmail.setForeground(new java.awt.Color(153, 153, 153));
        tfEmail.setCaretColor(new java.awt.Color(0, 153, 255));
        tfEmail.setDisabledTextColor(new java.awt.Color(0, 153, 255));
        tfEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfEmailActionPerformed(evt);
            }
        });

        lbPassword.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lbPassword.setForeground(new java.awt.Color(102, 102, 102));
        lbPassword.setText("Password");

        pfPassword.setForeground(new java.awt.Color(153, 153, 153));
        pfPassword.setCaretColor(new java.awt.Color(0, 153, 255));
        pfPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pfPasswordActionPerformed(evt);
            }
        });

        btLogin.setBackground(new java.awt.Color(0, 153, 255));
        btLogin.setForeground(new java.awt.Color(255, 255, 255));
        btLogin.setText("Login");
        btLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLoginActionPerformed(evt);
            }
        });

        lbForgotPass.setForeground(new java.awt.Color(153, 153, 153));
        lbForgotPass.setText("Forgot your password?");

        btReset.setForeground(new java.awt.Color(255, 51, 51));
        btReset.setText("Reset");
        btReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btResetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout LeftLayout = new javax.swing.GroupLayout(Left);
        Left.setLayout(LeftLayout);
        LeftLayout.setHorizontalGroup(
            LeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LeftLayout.createSequentialGroup()
                .addGroup(LeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LeftLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(lbForgotPass, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btReset))
                    .addGroup(LeftLayout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addComponent(lbLogin))
                    .addGroup(LeftLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(LeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lbEmail)
                            .addComponent(tfEmail)
                            .addComponent(lbPassword)
                            .addComponent(pfPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                            .addComponent(btLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        LeftLayout.setVerticalGroup(
            LeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LeftLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lbLogin)
                .addGap(20, 20, 20)
                .addComponent(lbEmail)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(lbPassword)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pfPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addGroup(LeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbForgotPass)
                    .addComponent(btReset))
                .addContainerGap(89, Short.MAX_VALUE))
        );

        Container.add(Left);
        Left.setBounds(300, 0, 300, 400);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Container, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Container, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfEmailActionPerformed

    private void btLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLoginActionPerformed
        // TODO add your handling code here:
        
        
       
        
         Main MainFrame =   new Main();
        MainFrame.setVisible(true);
       MainFrame.pack();
        MainFrame.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_btLoginActionPerformed

    private void btResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btResetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btResetActionPerformed

    private void pfPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pfPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pfPasswordActionPerformed

    /**
     * @param args the command line arguments
     */
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Container;
    private javax.swing.JPanel Left;
    private javax.swing.JPanel Right;
    private javax.swing.JButton btLogin;
    private javax.swing.JButton btReset;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lbCopyright;
    private javax.swing.JLabel lbDesignedBy;
    private javax.swing.JLabel lbEmail;
    private javax.swing.JLabel lbForgotPass;
    private javax.swing.JLabel lbICTLogo;
    private javax.swing.JLabel lbLogin;
    private javax.swing.JLabel lbLogos;
    private javax.swing.JLabel lbPassword;
    private javax.swing.JPasswordField pfPassword;
    private javax.swing.JTextField tfEmail;
    // End of variables declaration//GEN-END:variables
}
